def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger'
]

pipeline {
    agent any

    environment {
        cluster = 'enterprise-cicd-cluster'
        service = 'vprofile-task-service-gi6jxdoc'
    }

    stages {

        stage('Verify AWS Access') {
            steps {
                withAWS(credentials: 'aws-jenkins', region: 'ap-south-2') {
                    sh 'aws sts get-caller-identity'
                }
            }
        }

        stage('Deploy to ECS') {
            steps {
                withAWS(credentials: 'aws-jenkins', region: 'ap-south-2') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    post {
        success {
            slackSend(
                channel: '#jenkins-cicd',
                color: 'good',
                message: 'SUCCESS: ProdPipeline deployed VProfile to ECS.'
            )
        }

        failure {
            slackSend(
                channel: '#jenkins-cicd',
                color: 'danger',
                message: 'FAILURE: ProdPipeline deployment failed.'
            )
        }
    }
}