def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any

    environment {
        SNAP_REPO = 'maven-snapshots'
        RELEASE_REPO = 'maven-releases'
        CENTRAL_REPO = 'maven-central'

        NEXUSIP = 'ip-172-31-4-225.ap-south-2.compute.internal'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'maven-public'
        NEXUS_LOGIN = 'nexuslogin'

        SONARSERVER = 'SonarQube'
        SONARSCANNER = 'SonarScanner'

        registryCredential = 'ecr:ap-south-2:aws-jenkins'
        appRegistry = '499502048961.dkr.ecr.ap-south-2.amazonaws.com/vprofileappimg'
        vprofileRegistry = 'https://499502048961.dkr.ecr.ap-south-2.amazonaws.com'
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn -s pipeline/settings.xml -DskipTests install'
            }
            post {
                success {
                    echo 'Archiving WAR artifact...'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Test') {
            steps {
                sh 'mvn -s pipeline/settings.xml test'
            }
        }

        stage('Checkstyle Analysis') {
            steps {
                sh 'mvn -s pipeline/settings.xml checkstyle:checkstyle'
            }
        }

        stage('Sonar Analysis') {
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }

            steps {
                withSonarQubeEnv("${SONARSERVER}") {
                    sh """
                    ${scannerHome}/bin/sonar-scanner \
                    -Dsonar.projectKey=vprofile \
                    -Dsonar.projectName=vprofile \
                    -Dsonar.projectVersion=1.0 \
                    -Dsonar.sources=src/ \
                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                    -Dsonar.junit.reportsPath=target/surefire-reports/ \
                    -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    dockerImage = docker.build(
                        appRegistry + ":${BUILD_NUMBER}",
                        "./Docker-files/app/multistage/"
                    )
                }
            }
        }

        stage('Upload App Image') {
            steps {
                script {
                    docker.withRegistry(vprofileRegistry, registryCredential) {
                        dockerImage.push("${BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }
    }

    /*
    post {
        always {
            slackSend(
                channel: '#jenkinsci',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} Build ${env.BUILD_NUMBER}\n${env.BUILD_URL}"
            )
        }
    }
    */
}